version: '3.8'

networks:
  ashishpieshopnetwork:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver-container
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "MySQLServer1!"
    networks:
      - ashishpieshopnetwork
    volumes:
      - sqlserver-data:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
        test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P MySQLServer1! -C -Q 'SELECT 1'"]
        interval: 10s
        retries: 5

  ashishpieshop-web-app:
    image: ashishtvaghela/ashishpieshop-web-app:latest
    container_name: dotnet-webapp
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - sqlserver
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=AshishPieShop;User Id=sa;Password=MySQLServer1!;Encrypt=False;TrustServerCertificate=True;"
    networks:
      - ashishpieshopnetwork

volumes:
  sqlserver-data:
