name: Build and Deploy

on:
  push:
    branches:
      - testCICDWithDocker  # Trigger the workflow on pushes to the specified branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3
        
      # Step 4: Build Docker Image for Web App
      - name: Build Docker Image
        run: docker build -t ashishtvaghela/ashishpieshop-web-app:latest

      # Step 5: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 6: Push Docker Image to Docker Hub
      - name: Push Docker Image
        run: docker push ashishtvaghela/ashishpieshop-web-app:latest
